### ISSUE TITLE
📨  Ask A Question on iOS works only on Apple Mail App 📨

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/mobile#132]
See attached image. Could be an issue as a lot of people like to use 3rd party apps. 
Help? 
![unnamed](https://user-images.githubusercontent.com/47831068/98454356-a036eb80-2131-11eb-94fc-3ad557b78d08.jpg)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=590952438)

**Comment by JonEsparaz** [comment]
It works with Gmail for me, but the design calls for an in-app system anyways.

I already did the backend work for this a few months ago (https://github.com/themeetinghouse/web/pull/411), so we just need to build the UI, which isn't too much work.

**Comment by JonEsparaz** [comment]
@deeinstereo the ask a question functionality will be fixed in #163.

I'm interested to diagnose this issue in other parts of the app. Try going to More Screen, then tap Staff Team, then try tapping one of the mail icons:
- Does it work?
- If not, what 3rd party mail app are you trying to use?
- In your iOS settings, under default mail app, is your 3rd party mail app selected?

e.g. iOS Settings>Gmail>Default Mail App. You should see this:
<img src=https://user-images.githubusercontent.com/48423418/103806117-8ecf6a00-5022-11eb-8df3-6e32cfff73bb.png width=300>

**Comment by deeinstereo** [comment]
Hey Jon! This works for me, but the initial ask and screen shot came from someone else. I will follow up with them. 
I am using both the native Apple mail app and the Spark mail app.

**Comment by deeinstereo** [comment]
@JonEsparaz tested this and it now works! I also had the person who found the issue test it and it worked for them

**Comment by JonEsparaz** [comment]
Great! I assume this was just early iOS 14 bugs.
