### ISSUE TITLE
Determine why iOS is receiving an invalid response from Instagram scraper

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#43]
The Instagram works on web and Android (emulator) but not iOS (physical device).

Might require some native code. Still not entirely sure what the issue is.

**Comment by JonEsparaz** [comment]
Maybe Instagram had some downtime yesterday... It works now.

**Comment by JonEsparaz** [comment]
Issue seems to persist...

**Comment by JonEsparaz** [comment]
I determined what's wrong and it's quite frustrating. Any request to https://instagram.com on iOS returns the login page... This isn't the case on Android or desktop.

We might need a Lambda after all.

**Comment by GeorgeBellTMH** [comment]
Can you give it a different user-agent header?

**Comment by JonEsparaz** [comment]
Yeah that's what I'm going to try next. Will keep you updated.

**Comment by JonEsparaz** [comment]
Also, I think it was "working" on iOS this morning because I ran it on Android first, then iOS, so there was probably some caching or something.

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH I didn't have any luck with changing the UA.

Also, we could have a problem... I just tested the scraper in a Lambda and Instagram responded with the login page. I've had this issue with cloud functions on GCP too. I assume these limitations are intentional on Facebook's part since they probably want you to use the official API.

To support iOS (on the app and website), we probably need to write/read the data from DynamoDB, but we might not be able to do it from a Lambda. A silly, but surefire solution is running the scraper client side via the admin page, but this requires someone to trigger it manually (or at least open the page). We could setup a scheduled VM or cron job on a physical machine to trigger this action though...

Let me know if you have any ideas.

**Comment by georgevicbell** [comment]
They are making it a nightmare to do anything with them.

I saw this: https://stackoverflow.com/questions/49786980/how-to-perform-unauthenticated-instagram-web-scraping-in-response-to-recent-priv

Sent from my iPhone

On Aug 18, 2020, at 8:30 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

@GeorgeBellTMH<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGeorgeBellTMH&data=02%7C01%7C%7Cf3304a0fa56847697ab708d843d70b2a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637333938162925346&sdata=d7j%2BfVws%2FEvDCo5SXed4SYdbS6prL6HBP%2FpXl8gJxz4%3D&reserved=0> I didn't have any luck with changing the UA.

Also, we could have a problem... I just tested the scraper in a Lambda and Instagram responded with the login page. I've had this issue with cloud functions on GCP too. I assume these limitations are intentional on Facebook's part since they probably want you to use the official API.

To support iOS (on the app and website), we probably need to write/read the data from DynamoDB, but we might not be able to do it from a Lambda. A silly, but surefire solution is running the scraper client side via the admin page, but this requires someone to trigger it manually (or at least open the page). We could setup a scheduled VM or cron job on a physical machine to trigger this action though...

Let me know if you have any ideas.

**Comment by JonEsparaz** [comment]
I tried writing two new Lambda functions: one using Puppeteer and one using Playwright. Neither worked even though I am able to set the user agent (the response data from Instagram even indicated that it thinks the OS is Windows 10).

Example:

```javascript
const ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36'
const browser = await playwright.launchChromium();
const context = await browser.newContext({ userAgent: ua });
```

I assume Facebook is intentionally blocking requests from AWS Lambda or so many people have tried this on Lambda that the IPs get auto-blocked.

At this point, I think the best solution is some sort of "client-side" scraper that writes to DynamoDB, then we read from DynamoDB instead of continually scraping to ensure our domain doesn't get blocked by FB. The trick here is trying to automate it and running it often enough (probably 1-2 times per day) so that the images are up to date.

**Comment by GeorgeBellTMH** [comment]
Does the lambda work when you run it locally?

Sent from my iPhone

On Aug 19, 2020, at 5:01 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

I tried writing two new Lambda functions: one using Puppeteer and one using Playwright. Neither worked even though I am able to set the user agent (the response data from Instagram even indicated that it thinks the OS is Windows 10).

Example:

const ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36'
const browser = await playwright.launchChromium();
const context = await browser.newContext({ userAgent: ua });

I assume Facebook is intentionally blocking requests from AWS Lambda or so many people have tried this on Lambda that the IPs get auto-blocked.

At this point, I think the best solution is some sort of "client-side" scraper that writes to DynamoDB, then we read from DynamoDB instead of continually scraping to ensure our domain doesn't get blocked by FB. The trick here is trying to automate it and running it often enough (probably 1-2 times per day) so that the images are up to date.

**Comment by JonEsparaz** [comment]
> Does the lambda work when you run it locally?

Yup.

**Comment by JonEsparaz** [comment]
Node script doesn't work on EC2 either (returns login page). Still works locally.

Edit: Also doesn't work in a Lightsail VM. Safe to assume we can't run this kind of code on AWS servers.
