### ISSUE TITLE
Events Feature

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#97]
As per our approved UI design for this app found here: https://www.figma.com/file/EHr4QEEBfkAe9T5OTcVXah/Native-App?node-id=1%3A2:

Features:

* [x] The way events are populated should match what we are doing with the website. Currently, we set events in Facebook and then location pages pull events based on what facebook page the event is on. (I.e. The High Park web page pulls events from the High Park Facebook page).
* [x] Display events on home page with the following details:
* [x] Date
* [x] Title
* [x] Description
* [x] Address
* [x] Time
* [x] Display event icon on each event
* [x] Ability to add a picture to an event (probably best for now to pull the Facebook image somehow as the event is set in facebook)
* [x] Ability to click on event to see the following details:
* [x] Date icon
* [x] Title
* [x] Description
* [x] Date/Time
* [x] Add to calendar button allowing user to add event to their personal calendar
* [x] Address
* [x] Get Directions button allowing users to open their map with the address pre-populated
* [x] Ability to include a call to action button in events (i.e. register)
* [x] Ability to share the event (facebook, whatsapp, telegram, messenger, twitter, etc - what this actually mean? Does another user have to the app to see the event? Can we share the facebook version of the event for now?)
* [x] Ability to see a listing of all events on home page based on the site selected (but we need to account for users who have not yet selected a site)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588046673)

**Comment by georgevicbell** [comment]
I believe there is also a fallback for sites that don’t have any events, which is to use the main TMH site to pull events.

My assumption for users without a site selected is we also pull from the main TMH site.

Sent from my iPhone

On Oct 8, 2020, at 8:52 AM, Lucas Belem <notifications@github.com> wrote:

﻿

As per our approved UI design for this app found here: https://www.figma.com/file/EHr4QEEBfkAe9T5OTcVXah/Native-App?node-id=1%3A2<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.figma.com%2Ffile%2FEHr4QEEBfkAe9T5OTcVXah%2FNative-App%3Fnode-id%3D1%253A2&data=02%7C01%7C%7C2a57668a185542683f1608d86b891098%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637377583710891156&sdata=Zf1XyqHGfEWS8ojkV6wTKSnC8VnD3FOXfajPFzp4MR4%3D&reserved=0>:

Features:

  *   The way events are populated should match what we are doing with the website. Currently, we set events in Facebook and then location pages pull events based on what facebook page the event is on. (I.e. The High Park web page pulls events from the High Park Facebook page).
  *    Display events on home page with the following details:
  *   Date
  *   Title
  *   Description
  *   Address
  *   Time
  *    Display event icon on each event
  *    Ability to add a picture to an event (probably best for now to pull the Facebook image somehow as the event is set in facebook)
  *    Ability to click on event to see the following details:
  *   Date icon
  *   Title
  *   Description
  *   Date/Time
  *   Add to calendar button allowing user to add event to their personal calendar
  *   Address
  *   Get Directions button allowing users to open their map with the address pre-populated
  *    Ability to include a call to action button in events (i.e. register)
  *    Ability to share the event (facebook, whatsapp, telegram, messenger, twitter, etc - what this actually mean? Does another user have to the app to see the event? Can we share the facebook version of the event for now?)
  *    Ability to see a listing of all events on home page based on the site selected (but we need to account for users who have not yet selected a site)

**Comment by itbel** [comment]
Trying to work out where to pull the location from in order to open map with directions to the event but different events have the location stored in different places. I'm not sure how to account for this programmatically. 
```
Object {
  "description": "For more information, visit https://meetinghouse.infellowship.com/Forms/443068 or se........
  "end_time": "2020-10-20T21:30:00-0400",
  "id": "1154203511627430",
  "name": "Healing Care",
  "place": Object {
    "id": null,
    "location": null,
    "name": "2700 Bristol Cir, Oakville, ON L6H 6E1, Canada",
  },
  "start_time": "2020-10-18T14:00:00-0400",
}
```
```
Object {
  "description": "Calling all Kidmax kids! Dress up in your favourite costume and bring your grown-ups to Mohawk Park between 10am and 11:30am to get some candy and say hi to come Kidmax leaders!

We’d love to see you!",
  "end_time": null,
  "id": "340320160534395",
  "name": "Kidmax Drive-Thru Costume Party!",
  "place": Object {
    "id": "479512592070383",
    "location": Object {
      "city": "Brantford",
      "country": "Canada",
      "latitude": 43.13690727202,
      "longitude": -80.232604723051,
      "state": "ON",
      "street": "51 Lynnwood Drive",
      "zip": null,
    },
    "name": "Mohawk Park",
  },
  "start_time": "2020-10-31T10:00:00-0400",
}
```
```
Object {
  "description": "We will be hosting a FOOD DRIVE (Drive Thru) on Sunday, October 18th - between 1:00-3:00pm at 1240 ....
  "end_time": "2020-10-18T15:00:00-0400",
  "id": "4594551777285303",
  "name": "Food Drive - Drive Thru",
  "place": Object {
    "id": null,
    "location": null,
    "name": "1240 Advance Rd, Burlington, ON L7M 1G6, Canada",
  },
  "start_time": "2020-10-18T13:00:00-0400",
}
```
```
Object {
  "description": "We are hosting a COLLECTION DAY (Drive Thru) for Rescued & Restored on Sunday, November 15th 1:00-3:00pm. This collection of gently used furniture and household items will be donated to our Local Compassion Partner, Eagles Nest of Waterdown. For more information contact Jenn Stevens - jenn.stevens@themeetinghouse.com",
  "end_time": "2020-11-15T15:00:00-0500",
  "id": "828310261273962",
  "name": "Rescued & Restored Collection Day",
  "place": Object {
    "id": null,
    "location": null,
    "name": "1240 Advance Rd, Burlington, ON L7M 1G6, Canada",
  },
  "start_time": "2020-11-15T13:00:00-0500",
}
```
Is place.name the field that is used for location? Some locations might not be specific enough such as 
```
"name": "Mohawk Park",
```

Any thoughts? @GeorgeBellTMH

**Comment by georgevicbell** [comment]
My guess is that it’s a free form field on Facebook, but that you can also add an address (or it may sometimes autocomplete with more detailed information). I’d use the location if it’s set, and the name if it’s not.

If there is no gps details it’s probably better to not show it on the map...reverse lookups are expensive I think.

Sent from my iPhone

On Oct 13, 2020, at 7:16 PM, Igor Belem <notifications@github.com> wrote:

﻿

Trying to work out where to pull the location from in order to open map with directions to the event but different events have the location is stored in different places. I'm not sure how to account for this programmatically.

Object {
  "description": "For more information, visit https://meetinghouse.infellowship.com/Forms/443068 or se........
  "end_time": "2020-10-20T21:30:00-0400",
  "id": "1154203511627430",
  "name": "Healing Care",
  "place": Object {
    "id": null,
    "location": null,
    "name": "2700 Bristol Cir, Oakville, ON L6H 6E1, Canada",
  },
  "start_time": "2020-10-18T14:00:00-0400",
}


Object {
  "description": "Calling all Kidmax kids! Dress up in your favourite costume and bring your grown-ups to Mohawk Park between 10am and 11:30am to get some candy and say hi to come Kidmax leaders!

We’d love to see you!",
  "end_time": null,
  "id": "340320160534395",
  "name": "Kidmax Drive-Thru Costume Party!",
  "place": Object {
    "id": "479512592070383",
    "location": Object {
      "city": "Brantford",
      "country": "Canada",
      "latitude": 43.13690727202,
      "longitude": -80.232604723051,
      "state": "ON",
      "street": "51 Lynnwood Drive",
      "zip": null,
    },
    "name": "Mohawk Park",
  },
  "start_time": "2020-10-31T10:00:00-0400",
}


Object {
  "description": "We will be hosting a FOOD DRIVE (Drive Thru) on Sunday, October 18th - between 1:00-3:00pm at 1240 ....
  "end_time": "2020-10-18T15:00:00-0400",
  "id": "4594551777285303",
  "name": "Food Drive - Drive Thru",
  "place": Object {
    "id": null,
    "location": null,
    "name": "1240 Advance Rd, Burlington, ON L7M 1G6, Canada",
  },
  "start_time": "2020-10-18T13:00:00-0400",
}


Object {
  "description": "We are hosting a COLLECTION DAY (Drive Thru) for Rescued & Restored on Sunday, November 15th 1:00-3:00pm. This collection of gently used furniture and household items will be donated to our Local Compassion Partner, Eagles Nest of Waterdown. For more information contact Jenn Stevens - jenn.stevens@themeetinghouse.com",
  "end_time": "2020-11-15T15:00:00-0500",
  "id": "828310261273962",
  "name": "Rescued & Restored Collection Day",
  "place": Object {
    "id": null,
    "location": null,
    "name": "1240 Advance Rd, Burlington, ON L7M 1G6, Canada",
  },
  "start_time": "2020-11-15T13:00:00-0500",
}


Is place.name the field that is used for location? Some locations might not be specific enough such as

"name": "Mohawk Park",


Any thoughts? @GeorgeBellTMH<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGeorgeBellTMH&data=04%7C01%7C%7C1d09c09510204a5022f508d86fce0808%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637382277985613908%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vinE201DjC9pUJ6Yf1Ku1%2B1JdZdTVF81wT64PCV0iZw%3D&reserved=0>

**Comment by itbel** [comment]
I was planning on using this:
https://www.npmjs.com/package/react-native-open-maps
Opens with map coordinates or string query

**Comment by georgevicbell** [comment]
Sounds good. I would use whatever is more likely to be accurate then...gps, then name...

G

Sent from my iPhone

On Oct 13, 2020, at 7:46 PM, Igor Belem <notifications@github.com> wrote:

﻿

I was planning on using this:
https://www.npmjs.com/package/react-native-open-maps<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.npmjs.com%2Fpackage%2Freact-native-open-maps&data=04%7C01%7C%7Cddefb2682bc54966a68508d86fd23d6e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637382296056250457%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Fikn8YcykpvjiuGvqYAqhuNiMOX6QzM7ejrxaiUPc9A%3D&reserved=0>
Opens with map coordinates or string query

**Comment by itbel** [comment]
Okay thank you.
I also wanted to ask where is the function that pulls the event info from Facebook? I know event ids are stored in each site's JSON file on the web app. My current implementation pulls each site's respective JSON from themeetinghouse.com to get the event ids. This seems a bit cumbersome I was wondering how I could improve it.

**Comment by itbel** [comment]
@GeorgeBellTMH 
I was hoping to get some feedback on my implementation of the Add to Calendar feature and wondering if there could be a simpler way of doing it. 

I took a look at how this is implemented on themeetinghouse.com and read about react-native equivalent packages but the ones I found were not compatible with Expo. I found a working package specifically for expo called expo-calendar to make changes to the device calendar, and I have had some success. I'm still missing some validation, and logic to account for all possible cases but it seems to work.

The problem I see with this implementation at the moment is that the event is created in the background. (Instead of opening the calendar app with the event info auto-filled). On Android, this is not a big deal because it is possible to also instantly open the event in the calendar app to be edited after its creation, however, on iOS this does not seem possible with the expo-calendar package. I have read that it is possible to link using ```Linking.OpenURL('')``` to the calendar app to open at a certain date so this could be a work-around.
Here is what I have so far for reference: [(WIP) CalendarService.ts](https://github.com/itbel/tmh-mobile/commit/af4641196c4c764790e3dd4f08729393874ce0bb#diff-7d06bee182b19835473493cbdf912821a08fbd6712a45e9fa2411981d82a54f1)

@deeinstereo
I have come across events that have multiple instances. ie happening several times in a day or over the course of days. When adding the event to the calendar, should the end-time be the end-time of the last instance of the event? Or do we give the user the option to pick a specific event-time to be added to the calendar?

**Comment by GeorgeBellTMH** [comment]
Let me know which way you think is better, it might just be easier to pop up a modal in iOS that says "added to calendar" and leave it at that...if you think it's better to navigate them to it then lets do that...

**Comment by lucastbelem** [comment]
The modal idea sounds simple and faster? David, thoughts?

**Comment by deeinstereo** [comment]
Yeah let's go with the modal @itbel Also re end-times, if each one is a unique event then it should feature the start and end time and the user should pick which one they want to add. The way things are going it seems very probably that in the future we will run more events that have multiple start and end times to control the size of the groups.

**Comment by GeorgeBellTMH** [comment]
Pictures are now being loaded from FB...just need to add them to front-end.
